services:
  - type: web
    name: shaggy-dog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --workers 2 --threads 4 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
